# 虚拟环境 https://help.github.com/cn/articles/virtual-environments-for-github-actions
# action市场 https://github.com/marketplace?type=actions
# 自定义action https://help.github.com/cn/articles/metadata-syntax-for-github-actions
# action例子 https://github.com/actions
# github-nuget https://help.github.com/en/articles/configuring-nuget-for-use-with-github-package-registry
name: ASP.NET Core CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Install Nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - name: Setup Nuget
        run: nuget sources Add -Name "GPR" -Source "https://nuget.pkg.github.com/xxred/index.json" -UserName xxred -Password ${{secrets.GITHUB_TOKEN}}
      - name: Pack
        if: github
        run: |
          dotnet pack "Easy.Admin/Easy.Admin.csproj" -c Release -o pack
      - name: push to github
        run: |
          nuget push .\pack\*.nupkg -Source "GPR"
      - name: push to nuget.org
        run: |
          nuget push .\pack\*.nupkg "${{ secrets.nuget_token }}" -source https://api.nuget.org/v3/index.json
